export 'package:flutter/material.dart';
export 'dart:math';
export 'package:get/get.dart';
export 'package:fl_chart/fl_chart.dart';
export 'routes.dart';
export 'views/dashboard.dart';
export 'components/Widgets/water_consumption_chart.dart';
export 'components/Widgets/temp_gauge.dart';
export 'components/Widgets/humidity_gauge.dart';